### ISSUE TITLE
Design Proposal

### ISSUE THREAD

**Issue by mendezand** [vyvital/Fitz#1]
Hi.
If you need help in the graphic part I can support you. I can start creating a logo.

Greetings.

**Comment by vyvital** [comment]
Hello Mendez,
This sounds awesome! I will soon upload an APK to download before I put it in the Play Store, feel free to download it and redesign every activity, contact me at Fitzhelp247@gmail.com .
EDIT: I already have a nice logo, but I am open to suggestions :)
