### ISSUE TITLE
Where Can I write the basic functions in firebase in order to work this app . 

### ISSUE THREAD

**Issue by Adnan-addi** [vyvital/Fitz#4]
HI , 
i am having the same issue that desired functions are not fetched on my firebase account . 
can you just at least tell me where i can write the data in order to move on , on this app . 
it would be much help , rest i will take care off and your copyrights will not be effected .

Thank You.
Programmer is needy.

**Comment by vyvital** [comment]
Im not sure I understood your question, 

> write basic function in firebase

I don't have any functions in firebase, I only have the database in firebase, the database is located under `Develop>Database>Realtime Database` and it looks like in the example of #2 
The functions that are using firebase are in the relevant activities, so for login its in the login activity, for the programs its in the programs activity etc, just search for `Firebase` within the code.
The source code here is exactly the way the app works without any additions needed, the only thing missing is the DB which you need to create on Firebase, if you want another type of DB as in different categories and such you will need to adjust the firebase functions in the code to fit your needs.

You can learn how to write firebase function form the [docs](https://firebase.google.com/docs/database/android/read-and-write)  and just change the `child` calls to fit your hierarchy.
